
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2019.1.3
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
* 
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL 
*XILINX BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
*Except as contained in this notice, the name of the Xilinx shall not be used
*in advertising or otherwise to promote the sale, use or other dealings in
*this Software without prior written authorization from Xilinx.
*

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxidma.h"

/*
* The configuration table for devices
*/

XAxiDma_Config XAxiDma_ConfigTable[XPAR_XAXIDMA_NUM_INSTANCES] =
{
	{
		XPAR_ZMODADC_0_AXI_DMA_ADC_DEVICE_ID,
		XPAR_ZMODADC_0_AXI_DMA_ADC_BASEADDR,
		XPAR_ZMODADC_0_AXI_DMA_ADC_SG_INCLUDE_STSCNTRL_STRM,
		XPAR_ZMODADC_0_AXI_DMA_ADC_INCLUDE_MM2S,
		XPAR_ZMODADC_0_AXI_DMA_ADC_INCLUDE_MM2S_DRE,
		XPAR_ZMODADC_0_AXI_DMA_ADC_M_AXI_MM2S_DATA_WIDTH,
		XPAR_ZMODADC_0_AXI_DMA_ADC_INCLUDE_S2MM,
		XPAR_ZMODADC_0_AXI_DMA_ADC_INCLUDE_S2MM_DRE,
		XPAR_ZMODADC_0_AXI_DMA_ADC_M_AXI_S2MM_DATA_WIDTH,
		XPAR_ZMODADC_0_AXI_DMA_ADC_INCLUDE_SG,
		XPAR_ZMODADC_0_AXI_DMA_ADC_NUM_MM2S_CHANNELS,
		XPAR_ZMODADC_0_AXI_DMA_ADC_NUM_S2MM_CHANNELS,
		XPAR_ZMODADC_0_AXI_DMA_ADC_MM2S_BURST_SIZE,
		XPAR_ZMODADC_0_AXI_DMA_ADC_S2MM_BURST_SIZE,
		XPAR_ZMODADC_0_AXI_DMA_ADC_MICRO_DMA,
		XPAR_ZMODADC_0_AXI_DMA_ADC_ADDR_WIDTH,
		XPAR_ZMODADC_0_AXI_DMA_ADC_SG_LENGTH_WIDTH
	},
	{
		XPAR_AXI_DMA_DPTI_DEVICE_ID,
		XPAR_AXI_DMA_DPTI_BASEADDR,
		XPAR_AXI_DMA_DPTI_SG_INCLUDE_STSCNTRL_STRM,
		XPAR_AXI_DMA_DPTI_INCLUDE_MM2S,
		XPAR_AXI_DMA_DPTI_INCLUDE_MM2S_DRE,
		XPAR_AXI_DMA_DPTI_M_AXI_MM2S_DATA_WIDTH,
		XPAR_AXI_DMA_DPTI_INCLUDE_S2MM,
		XPAR_AXI_DMA_DPTI_INCLUDE_S2MM_DRE,
		XPAR_AXI_DMA_DPTI_M_AXI_S2MM_DATA_WIDTH,
		XPAR_AXI_DMA_DPTI_INCLUDE_SG,
		XPAR_AXI_DMA_DPTI_NUM_MM2S_CHANNELS,
		XPAR_AXI_DMA_DPTI_NUM_S2MM_CHANNELS,
		XPAR_AXI_DMA_DPTI_MM2S_BURST_SIZE,
		XPAR_AXI_DMA_DPTI_S2MM_BURST_SIZE,
		XPAR_AXI_DMA_DPTI_MICRO_DMA,
		XPAR_AXI_DMA_DPTI_ADDR_WIDTH,
		XPAR_AXI_DMA_DPTI_SG_LENGTH_WIDTH
	}
};


