set_property SRC_FILE_INFO {cfile:{C:/Users/Francis Choi/Desktop/Cap/ZmodADC2019.1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/constrs_1/new/USB104A7_A.xdc} rfile:../../../USB104A7_ZmodADC_Demo.srcs/constrs_1/new/USB104A7_A.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/Francis Choi/Desktop/Cap/ZmodADC2019.1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/constrs_1/imports/temp/ZmodADC_0_ZmodADC.xdc} rfile:../../../USB104A7_ZmodADC_Demo.srcs/constrs_1/imports/temp/ZmodADC_0_ZmodADC.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V16   IOSTANDARD LVCMOS33 } [get_ports { btn0 }]; #IO_L16N_T2_A15_D31_14 Sch=btn[0]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports prog_clko]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD LVCMOS33} [get_ports {prog_d[0]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R12 IOSTANDARD LVCMOS33} [get_ports {prog_d[1]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVCMOS33} [get_ports {prog_d[2]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {prog_d[3]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {prog_d[4]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {prog_d[5]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports {prog_d[6]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {prog_d[7]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports prog_oen]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports prog_rdn]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports prog_rxen]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports prog_siwun]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports prog_spien]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports prog_txen]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports prog_wrn]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS33 PULLUP TRUE } [get_ports { Zmod_IIC_scl_io }]; #IO_L18P_T2_A12_D28_14 Sch=syzygy_scl
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V17   IOSTANDARD LVCMOS33 PULLUP TRUE } [get_ports { Zmod_IIC_sda_io }]; #IO_L18N_T2_A11_D27_14 Sch=syzygy_sda
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A13 [get_ports {ZmodADC_0_SC1_AC_H_0}];
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports {ZmodADC_0_SC1_AC_L_0}] ; #IO_L9N_T1_DQS_AD3N_15 Sch=syzygy_d_n[0]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B16 [get_ports {ZmodADC_0_SC2_AC_H_0}] ; #IO_L7P_T1_AD2P_15 Sch=syzygy_d_p[1]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B17 [get_ports {ZmodADC_0_SC2_AC_L_0}] ; #IO_L7N_T1_AD2N_15 Sch=syzygy_d_n[1]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15 [get_ports {ZmodADC_0_SC1_GAIN_H_0}]; #IO_L12P_T1_MRCC_15 Sch=syzygy_d_p[5]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C15 [get_ports {ZmodADC_0_SC1_GAIN_L_0}]; #IO_L12N_T1_MRCC_15 Sch=syzygy_d_n[5]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18 [get_ports {ZmodADC_0_SC2_GAIN_H_0}]; #IO_L10P_T1_AD11P_15 Sch=syzygy_d_p[3]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports {ZmodADC_0_SC2_GAIN_L_0}]; #IO_L10N_T1_AD11N_15 Sch=syzygy_d_n[3]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports {ZmodADC_0_SC_COM_H_0}]; #IO_L21P_T3_DQS_15 Sch=syzygy_d_p[7]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {ZmodADC_0_SC_COM_L_0}]; #IO_L21N_T3_DQS_A18_15 Sch=syzygy_d_n[7]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A15 [get_ports {ZmodADC_0_sdio_sc_0}]; #IO_L8P_T1_AD10P_15 Sch=syzygy_d_p[2]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E17 [get_ports {ZmodADC_0_cs_sc1_0}]; #IO_L16P_T2_A28_15 Sch=syzygy_s[26]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A16 [get_ports {ZmodADC_0_sclk_sc_0}]; #IO_L8N_T1_AD10N_15 Sch=syzygy_d_n[2]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D17   [get_ports {ZmodADC_0_ADC_SYNC_0}]; #IO_L16N_T2_A27_15 Sch=syzygy_s[27]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports ZmodADC_0_ADC_DCO_0]; #IO_L13P_T2_MRCC_15 Sch=syzygy_p2c_clk_p
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F15 [get_ports {ZmodADC_0_CLKIN_ADC_P_0}]; #IO_L14P_T2_SRCC_15 Sch=syzygy_c2p_clk_p
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F16   [get_ports {ZmodADC_0_CLKIN_ADC_N_0}]; #IO_L14N_T2_SRCC_15 Sch=syzygy_c2p_clk_n
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H14 [get_ports {ZmodADC_0_ADC_DATA_0[0]}]; #IO_L15P_T2_DQS_15 Sch=syzygy_s[24]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K15 [get_ports {ZmodADC_0_ADC_DATA_0[1]}]; #IO_L24P_T3_RS1_15 Sch=syzygy_s[22]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E16 [get_ports {ZmodADC_0_ADC_DATA_0[2]}]; #IO_L11N_T1_SRCC_15 Sch=syzygy_d_n[4]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C16 [get_ports {ZmodADC_0_ADC_DATA_0[3]}]; #IO_L20P_T3_A20_15 Sch=syzygy_d_p[6]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C17 [get_ports {ZmodADC_0_ADC_DATA_0[4]}]; #IO_L20N_T3_A19_15 Sch=syzygy_d_n[6]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J14 [get_ports {ZmodADC_0_ADC_DATA_0[5]}]; #IO_L19P_T3_A22_15 Sch=syzygy_s[16]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18 [get_ports {ZmodADC_0_ADC_DATA_0[6]}]; #IO_L22P_T3_A17_15 Sch=syzygy_s[18]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J17 [get_ports {ZmodADC_0_ADC_DATA_0[7]}]; #IO_L23P_T3_FOE_B_15 Sch=syzygy_s[20]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports {ZmodADC_0_ADC_DATA_0[8]}]; #IO_L19N_T3_A21_VREF_15 Sch=syzygy_s[17]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports {ZmodADC_0_ADC_DATA_0[9]}]; #IO_L11P_T1_SRCC_15 Sch=syzygy_d_p[4]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F18 [get_ports {ZmodADC_0_ADC_DATA_0[10]}]; #IO_L22N_T3_A16_15 Sch=syzygy_s[19]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports {ZmodADC_0_ADC_DATA_0[11]}]; #IO_L23N_T3_FWE_B_15 Sch=syzygy_s[21]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {ZmodADC_0_ADC_DATA_0[12]}]; #IO_L24N_T3_RS0_15 Sch=syzygy_s[23]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {ZmodADC_0_ADC_DATA_0[13]}]; #IO_L15N_T2_DQS_ADV_B_15 Sch=syzygy_s[25]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name ZmodADC_0_CLKIN_ADC_P_0 -source [get_pins design_1_i/ZmodADC_0/ZmodADC1410_Controll_1/U0/InstADC_ClkODDR/C] -divide_by 1 [get_ports ZmodADC_0_CLKIN_ADC_P_0]
