# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/design_1_AXI_ZmodADC1410_1_0.xci
# IP: The module: 'design_1_AXI_ZmodADC1410_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/TX_FIFO/TX_FIFO.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TX_FIFO || ORIG_REF_NAME==TX_FIFO} -quiet] -quiet

# IP: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/RX_FIFO/RX_FIFO.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RX_FIFO || ORIG_REF_NAME==RX_FIFO} -quiet] -quiet

# IP: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/TX_FIFO/TX_FIFO.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TX_FIFO || ORIG_REF_NAME==TX_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/TX_FIFO/TX_FIFO_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TX_FIFO || ORIG_REF_NAME==TX_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/RX_FIFO/RX_FIFO.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RX_FIFO || ORIG_REF_NAME==RX_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/RX_FIFO/RX_FIFO_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RX_FIFO || ORIG_REF_NAME==RX_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# IP: C:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/design_1_AXI_ZmodADC1410_1_0.xci
# IP: The module: 'design_1_AXI_ZmodADC1410_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/TX_FIFO/TX_FIFO.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TX_FIFO || ORIG_REF_NAME==TX_FIFO} -quiet] -quiet

# IP: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/RX_FIFO/RX_FIFO.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RX_FIFO || ORIG_REF_NAME==RX_FIFO} -quiet] -quiet

# IP: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/TX_FIFO/TX_FIFO.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TX_FIFO || ORIG_REF_NAME==TX_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/TX_FIFO/TX_FIFO_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==TX_FIFO || ORIG_REF_NAME==TX_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/RX_FIFO/RX_FIFO.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RX_FIFO || ORIG_REF_NAME==RX_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/RX_FIFO/RX_FIFO_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==RX_FIFO || ORIG_REF_NAME==RX_FIFO} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_AXI_ZmodADC1410_1_0/src/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
