# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_ZmodADC1410_Controll_1_0/design_1_ZmodADC1410_Controll_1_0.xci
# IP: The module: 'design_1_ZmodADC1410_Controll_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_ZmodADC1410_Controll_1_0/src/fifo_generator_adc/fifo_generator_adc.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_adc || ORIG_REF_NAME==fifo_generator_adc} -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_ZmodADC1410_Controll_1_0/src/fifo_generator_adc/fifo_generator_adc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_adc || ORIG_REF_NAME==fifo_generator_adc} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_ZmodADC1410_Controll_1_0/src/fifo_generator_adc/fifo_generator_adc_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_adc || ORIG_REF_NAME==fifo_generator_adc} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: C:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_ZmodADC1410_Controll_1_0/design_1_ZmodADC1410_Controll_1_0.xci
# IP: The module: 'design_1_ZmodADC1410_Controll_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_ZmodADC1410_Controll_1_0/src/fifo_generator_adc/fifo_generator_adc.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_adc || ORIG_REF_NAME==fifo_generator_adc} -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_ZmodADC1410_Controll_1_0/src/fifo_generator_adc/fifo_generator_adc.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_adc || ORIG_REF_NAME==fifo_generator_adc} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Francis Choi/Desktop/Capstone/USB104A7-ZmodADC-v2019.1-1/FPGA/vivado_proj/USB104A7_ZmodADC_Demo.srcs/sources_1/bd/design_1/ip/design_1_ZmodADC1410_Controll_1_0/src/fifo_generator_adc/fifo_generator_adc_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_adc || ORIG_REF_NAME==fifo_generator_adc} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
